apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eve-registry
  namespace: eve
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - registry.eh1.incept5.dev
      secretName: eve-registry-tls
  rules:
    - host: registry.eh1.incept5.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eve-registry
                port:
                  number: 5000
