apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eve-api
  namespace: eve
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - $patch: replace
      host: api.eve.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eve-api
                port:
                  number: 4701
