apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eve-org-fs-org-default
  namespace: eve
  labels:
    app.kubernetes.io/name: eve-org-fs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
