apiVersion: v1
kind: Service
metadata:
  name: eve-api
  namespace: eve
  labels:
    app.kubernetes.io/name: eve-api
spec:
  selector:
    app.kubernetes.io/name: eve-api
  ports:
    - name: http
      port: 4701
      targetPort: http
