apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: buildkitd-restrict-ingress
  namespace: eve
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: buildkitd
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eve-worker
      ports:
        - protocol: TCP
          port: 1234
