apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: eve
  labels:
    app.kubernetes.io/name: buildkitd
spec:
  selector:
    app.kubernetes.io/name: buildkitd
  ports:
    - name: grpc
      port: 1234
      targetPort: grpc
