apiVersion: v1
kind: Service
metadata:
  name: eve-orchestrator
  namespace: eve
  labels:
    app.kubernetes.io/name: eve-orchestrator
spec:
  selector:
    app.kubernetes.io/name: eve-orchestrator
  ports:
    - name: http
      port: 4702
      targetPort: http
