apiVersion: v1
kind: ConfigMap
metadata:
  name: eve-registry-config
  namespace: eve
  labels:
    app.kubernetes.io/name: eve-registry
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      s3:
        region: eu-west-1
        bucket: REPLACE_REGISTRY_BUCKET
        encrypt: true
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: true
    http:
      addr: :5000
    auth:
      token:
        realm: https://api.eve.example.com/internal/registry/token
        service: eve-registry
        issuer: eve-api
        rootcertbundle: /etc/registry/signing-cert.pem
