apiVersion: v1
kind: Service
metadata:
  name: eve-registry
  namespace: eve
  labels:
    app.kubernetes.io/name: eve-registry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: eve-registry
  ports:
    - name: registry
      protocol: TCP
      port: 5000
      targetPort: 5000
