apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-registry
  namespace: eve
  labels:
    app.kubernetes.io/name: eve-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eve-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eve-registry
    spec:
      serviceAccountName: eve-registry
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - name: registry
              containerPort: 5000
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry
            - name: signing-cert
              mountPath: /etc/registry/signing-cert.pem
              subPath: cert.pem
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: eve-registry-config
            items:
              - key: config.yml
                path: config.yml
        - name: signing-cert
          secret:
            secretName: eve-registry-cert
